FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc libpq-dev postgresql-client \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p config

COPY config/logger_config.json ./config/logger_config.json

COPY pyproject.toml ./
RUN pip install --no-cache-dir --upgrade pip setuptools wheel && pip install --no-cache-dir -e .

COPY ./app ./app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
